on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
    
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install and test
      run: |
        npm install
        npm run test
        
    - name: ftp-action
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ftp.vaifeed1.hospedagemdesites.ws
        # FTP user
        user: vaifeed1
        # FTP password
        password: Pass123456789@
        # Remote directory
        remoteDir: testing/
