on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
    
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install and test
      run: |
        npm install
        npm run test
        
    - name: studies-lwftp-testing
      uses: allanalves23/ftp-action-studies@0.0.2
      with:
        host: "ftp.vaifeed1.hospedagemdesites.ws"
        user: "vaifeed1"
        password: "Pass123456789@"
        localDir: "src"
        remoteDir: "testing"
        
